##### p2p_supplicant configuration - Meizu M6 (meizu_m6) #####
update_config=1
ctrl_interface=/data/vendor/wifi/wpa/sockets
driver_param=use_p2p_group_interface=1

device_name=Meizu M6
manufacturer=Meizu
model_name=meizu_m6
model_number=M711
serial_number=
device_type=10-0050F204-5
config_methods=physical_display virtual_push_button
p2p_no_group_iface=1
